export const LOGIN_SUBMITTING = 'LOGIN_SUBMITTING';

export const SQ_CHANGE_QUERYDATA = 'SQ_CHANGE_QUERYDATA';
export const SQ_CHANGE_DATA = 'SQ_CHANGE_DATA';
export const SQ_CHANGE_DATA_TOTAL = 'SQ_CHANGE_DATA_TOTAL';

export const KQ_CHANGE_QUERYDATA = 'KQ_CHANGE_QUERYDATA';
export const KQ_CHANGE_DATA = 'KQ_CHANGE_DATA';
export const KQ_CHANGE_DATA_TOTAL = 'KQ_CHANGE_DATA_TOTAL';
