// 登录
export const LOGIN_SUBMITTING = 'LOGIN_SUBMITTING';

// 订单查询 状态查询
export const SQ_CHANGE_QUERYDATA = 'SQ_CHANGE_QUERYDATA';
export const SQ_CHANGE_DATA = 'SQ_CHANGE_DATA';
export const SQ_CHANGE_DATA_TOTAL = 'SQ_CHANGE_DATA_TOTAL';

// 订单查询 关键字查询
export const KQ_CHANGE_QUERYDATA = 'KQ_CHANGE_QUERYDATA';
export const KQ_CHANGE_DATA = 'KQ_CHANGE_DATA';
export const KQ_CHANGE_DATA_TOTAL = 'KQ_CHANGE_DATA_TOTAL';

// 订单详情
export const OD_SET_ORDERDETAIL = 'OD_SET_ORDERDETAIL';

// 订单调度 订单列表
export const OD_CHANGE_QUERYDATA = 'OD_CHANGE_QUERYDATA';
export const OD_CHANGE_DATA = 'OD_CHANGE_DATA';
export const OD_CHANGE_DATA_TOTAL = 'OD_CHANGE_DATA_TOTAL';

// 订单调度 订单详情 分配配送员
export const OD_GET_ORDERINFO = 'OD_GET_ORDERINFO';
export const OD_SET_QUERYDATA = 'OD_SET_QUERYDATA';
export const OD_GET_ALLOTABLE_COURIER = 'OD_GET_ALLOTABLE_COURIER';
export const OD_GET_ALLOTABLE_COURIER_TOTAL = 'OD_GET_ALLOTABLE_COURIER_TOTAL';

// 共同
export const CM_SET_VOICE_SWITCH = 'CM_SET_VOICE_SWITCH';
