export const CHANGE_QUERYDATA = 'CHANGE_QUERYDATA';
export const CHANGE_DATA = 'CHANGE_DATA';
export const CHANGE_DATA_TOTAL = 'CHANGE_DATA_TOTAL';

export default { CHANGE_QUERYDATA, CHANGE_DATA, CHANGE_DATA_TOTAL };
